# Lesson 2 teaches the user the letter A to J

lesson_2_timeline = {
    1: "Welcome to lesson 2 where you will be taught the letters A to J in braille.",
    2: "These combinations are the building blocks for all the other letters.",
    3: "Once you learn these the rest will be easier.",
    4: "Firstly, make sure all dots are lowered. An empty cell.",
    5: 1,
    6: "Nicely done. Now we begin.",
    8: "In braille the letter A is represented by a single DOT. The top left dot raised represents the letter A.",
    9: "Try it now and raise the top left dot.",
    10: 33,
    11: "Fantastic. This represents the letter A in Braille.",
    12: "In braille the letter B is represented by two DOTs. When the top left dot and the middle left dot are raised this represents the letter B.",
    14: 8,
    15: "Nice one this is the letter B.",
    18: "The letter C is represented by 2 dots. The top 2 dots.",
    19: 9,
    20: "Well done. That is the letter C in braille",
    21: "Up next is the letter D. The letter D is dot 1, 4 and 5. Try it now.",
    22: 10,
    23: "Perfect. That is letter D.",
    24: "Up next is the letter E. The letter E is dot 1and 5. Try it now.",
    25: 11,
    26: "Perfect. That is letter E.",
    27: "Up next is the letter F. The letter F is dot 1, 2 and 4. Try it now.",
    28: 12,
    29: "Perfect. That is letter F.", 
    30: "Up next is the letter G. The letter G is dot 1, 2, 4 and 5. Try it now.",
    31: 13,
    32: "Perfect. That is letter G.",
    33: "Up next is the letter H. The letter H is dot 1, 2 and 5. Try it now.",
    34: 14,
    35: "Perfect. That is letter H.",
    36: "Up next is the letter I. The letter I is dot 2 and 4. Try it now.",
    37: 15,
    38: "Perfect. That is letter I.",
    39: "Up next is the letter J. The letter J is dot 2, 4 and 5. Try it now.",
    40: 16,
    41: "Perfect. That is letter J.",
    42: "You have now been shown the letters A to J. Try a quiz to see what ones you can remember.",
}
