# Lesson 3 teaches the user the letter K to T

lesson_3_timeline = {
    1: "Welcome to lesson 3 where you will be taught the letters K to T in braille.",
    2: "The pattern of letters K to T is just like A to J however with dot 3 also high",
    3: "for instance letter K is letter a but with dot 3 also high",
    4: "Firstly, make sure all dots are lowered. An empty cell.",
    5: 1,
    6: "Nicely done. Now we begin.",
    8: "In braille the letter K is represented by dot 1 and dot 3.",
    9: "Try it now and raise dot 1 and dot 3.",
    10: 17,
    11: "Fantastic. This represents the letter A in Braille.",
    12: "In braille the letter L is represented by Three DOTs. When Dot 1, Dot 2 and Dot 3 are raised this represents the letter L.",
    14: 18,
    15: "Nice one this is the letter L.",
    18: "The letter M is represented by 3 dots. Dot 1, Dot 3 and Dot 4.",
    19: 19,
    20: "Well done. That is the letter M in braille",
    21: "Up next is the letter N. The letter M is dot 1, 3, 4 and 5. Try it now.",
    22: 20,
    23: "Perfect. That is letter N.",
    24: "Up next is the letter O. The letter O is dot 1, 3 and 5. Try it now.",
    25: 21,
    26: "Perfect. That is letter O.",
    27: "Up next is the letter P. The letter P is dot 1, 2, 3 and 4. Try it now.",
    28: 22,
    29: "Perfect. That is letter P.",
    30: "Up next is the letter Q. The letter Q is dot 1, 2, 3, 4 and 5. Try it now.",
    31: 23,
    32: "Perfect. That is letter Q.",
    33: "Up next is the letter R. The letter R is dot 1, 2, 3 and 5. Try it now.",
    34: 24,
    35: "Perfect. That is letter R.",
    36: "Up next is the letter S. The letter S is dot 2, 3 and 4. Try it now.",
    37: 25,
    38: "Perfect. That is letter S.",
    39: "Up next is the letter T. The letter T is dot 2, 3, 4 and 5. Try it now.",
    40: 26,
    41: "Perfect. That is letter T.",
    42: "You have now been shown the letters K to T. Try a quiz to see what ones you can remember.",
}
