# Lesson 4 teaches the user the letter U to Z

lesson_4_timeline = {
    1: "Welcome to lesson 4 where you will be taught the letters U to Z in braille.",
    2: "The pattern of letters U to Z is just like A to J however with dot 3 and 6 also high",
    3: "for instance letter U is letter A but with dot 3 and 6 also high",
    4: "Firstly, make sure all dots are lowered. An empty cell.",
    5: 1,
    6: "Nicely done. Now we begin.",
    8: "In braille the letter U is represented by dot 1, 3 and dot 6.",
    9: "Try it now and raise dot 1, 3 and dot 6.",
    10: 27,
    11: "Fantastic. This represents the letter U in Braille.",
    12: "In braille the letter V is represented by 4 DOTs. When Dot 1, Dot 2, Dot 3 and Dot 6 are raised this represents the letter V.",
    14: 28,
    15: "Nice one this is the letter V.",
    18: "The letter X is represented by 4 dots. Dot 1, Dot 3, Dot 4, and Dot 6.",
    19: 29,
    20: "Well done. That is the letter X in braille",
    21: "Up next is the letter Y. The letter Y is dot 1, 3, 4, 5 and 6. Try it now.",
    22: 30,
    23: "Perfect. That is letter Y.",
    24: "Up next is the letter Z. The letter Z is dot 1, 3, 5 and 6. Try it now.",
    25: 31,
    26: "Perfect. That is letter Z.",
    27: "Up next is the letter W. The letter W is dot 2, 4, 5 and 6. Try it now.",
    28: 32,
    29: "Perfect. That is letter W.",
    30: "You have now been shown the letters U to W. Try a quiz to see what ones you can remmeber.",
}
