# This lesson helps the user get familiar with the system.

lesson_0_tutorial = {
    1: "To get you familiar with the six dots we will go through a tutorial where we will press them one by one.",
    2: "Firstly, make sure all the dots have been pushed down. This is known as an empty cell.",
    3: 1,
    4: "Awesome. it looks like you are ready to begin",
    5: "The top left dot is known as dot 1. Please raise this dot now so that it is the only dot which is high.",
    6: 2,
    7: "Fantastic. This is dot 1.",
    8: "Now as we did previously make sure all the dots are pressed down. The empty cell.",
    9: 1,
    10: "Great. The next dot is dot 2. Dot 2 is located on the left column, second row down.",
    11: 3,
    12: "Well done, this is dot 2.",
    13: "Now as we did previously make sure all the dots are pressed down. An empty cell.",
    14: 1,
    15: "Great. The next dot is dot 3. Dot 3 is located at the bottum left of the cell.",
    16: 4,
    17: "Now as we did previously make sure all the dots are pressed down. An empty cell.",
    18: 1,
    19: "Great. The next dot is dot 4. Dot 4 is located at the top right of the cell.",
    20: 5,
    21: "Good work. Now as we did previously make sure all the dots are pressed down. An empty cell.",
    22: 1,
    23: "Great. The next dot is dot 5. Dot 5 is located on the right column, second row down.",
    24: 6,
    25: "Well done that was dot 5. Now as we did previously make sure all the dots are pressed down. An empty cell.",
    26: 1,
    27: "Well done thats the one. Last but not least is is dot 6. Dot 6 is located at the bottum right of the cell.",
    28: 7,
    29: "YOU DID IT. Your first braille lesson. Congratulations.",
}
